# Generated by Django 4.2.16 on 2024-10-31 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vakansi',
            name='image',
            field=models.ImageField(null=True, upload_to='static/images'),
        ),
    ]
