# Generated by Django 4.2.16 on 2024-10-31 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_vakansi_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vakansi',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/images'),
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('resume', models.FileField(null=True, upload_to='static/images')),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('vakansi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.vakansi')),
            ],
        ),
    ]
