# Generated by Django 4.2.16 on 2024-11-01 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_vakansi_image_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='static/images'),
        ),
    ]
