# Generated by Django 4.2.16 on 2024-11-08 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_worker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='vakansi',
        ),
        migrations.AddField(
            model_name='worker',
            name='company',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='desc',
            field=models.TextField(null=True),
        ),
    ]
